# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_windows(object):
    def setupUi(self, Main_windows):
        Main_windows.setObjectName("Main_windows")
        Main_windows.setWindowModality(QtCore.Qt.NonModal)
        Main_windows.resize(342, 240)
        Main_windows.setMinimumSize(QtCore.QSize(342, 240))
        Main_windows.setMaximumSize(QtCore.QSize(342, 240))
        Main_windows.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2 = QtWidgets.QLabel(Main_windows)
        self.label_2.setGeometry(QtCore.QRect(3, 80, 54, 20))
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(Main_windows)
        self.progressBar.setGeometry(QtCore.QRect(140, 130, 191, 20))
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Main_windows)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(50, 190, 62, 21))
        self.doubleSpinBox_2.setMaximum(100.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.toolButton = QtWidgets.QToolButton(Main_windows)
        self.toolButton.setGeometry(QtCore.QRect(290, 30, 37, 18))
        self.toolButton.setObjectName("toolButton")
        self.radioButton_4 = QtWidgets.QRadioButton(Main_windows)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 100, 89, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_4 = QtWidgets.QLabel(Main_windows)
        self.label_4.setGeometry(QtCore.QRect(8, 160, 54, 20))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(Main_windows)
        self.spinBox.setGeometry(QtCore.QRect(50, 130, 61, 22))
        self.spinBox.setMaximum(50)
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_2 = QtWidgets.QLineEdit(Main_windows)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 80, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(Main_windows)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 180, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_5 = QtWidgets.QRadioButton(Main_windows)
        self.radioButton_5.setGeometry(QtCore.QRect(180, 100, 89, 21))
        self.radioButton_5.setObjectName("radioButton_5")
        self.label_3 = QtWidgets.QLabel(Main_windows)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 54, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Main_windows)
        self.label.setGeometry(QtCore.QRect(8, 30, 54, 20))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Main_windows)
        self.doubleSpinBox.setGeometry(QtCore.QRect(50, 160, 62, 22))
        self.doubleSpinBox.setMaximum(200.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.lineEdit = QtWidgets.QLineEdit(Main_windows)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 241, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton_2 = QtWidgets.QToolButton(Main_windows)
        self.toolButton_2.setGeometry(QtCore.QRect(290, 80, 37, 18))
        self.toolButton_2.setObjectName("toolButton_2")
        self.pushButton = QtWidgets.QPushButton(Main_windows)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(Main_windows)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 241, 20))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Main_windows)
        self.label_5.setGeometry(QtCore.QRect(8, 190, 54, 20))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Main_windows)
        self.label_9.setGeometry(QtCore.QRect(140, 150, 161, 21))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Main_windows)
        QtCore.QMetaObject.connectSlotsByName(Main_windows)

    def retranslateUi(self, Main_windows):
        _translate = QtCore.QCoreApplication.translate
        Main_windows.setWindowTitle(_translate("Main_windows", "Wannacri GUI"))
        self.label_2.setText(_translate("Main_windows", "Output"))
        self.toolButton.setText(_translate("Main_windows", "..."))
        self.radioButton_4.setText(_translate("Main_windows", "VP9 USM"))
        self.label_4.setText(_translate("Main_windows", "Volmue："))
        self.pushButton_2.setText(_translate("Main_windows", "Convert"))
        self.radioButton_5.setText(_translate("Main_windows", "H264 USM"))
        self.label_3.setText(_translate("Main_windows", " CRF："))
        self.label.setText(_translate("Main_windows", "Input"))
        self.toolButton_2.setText(_translate("Main_windows", "..."))
        self.pushButton.setText(_translate("Main_windows", "Exit"))
        self.label_7.setText(_translate("Main_windows", "Video：ready to check......"))
        self.label_5.setText(_translate("Main_windows", "Bright："))
        self.label_9.setText(_translate("Main_windows", "Check FFmpeg......"))


if __name__ == "__main__":
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    AddEditMovieDlg = QtWidgets.QDialog()
    ui = Ui_Main_windows()
    ui.setupUi(AddEditMovieDlg)
    AddEditMovieDlg.show()
    sys.exit(app.exec())